### ISSUE TITLE
Checkboxes don't save on Settings Page

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-braintree#6] opened 2016-02-12 17:38 UTC
The checkboxes don't save as "Checked" on the settings page.
"Submit for Settlement" and "Store In Vault on Success"

This appears to be a new issue with EDD 2.5.7 as using 2.5.6 allows them to save correctly.

<img width="946" alt="screen shot 2016-02-12 at 11 57 08 am" src="https://cloud.githubusercontent.com/assets/1638128/13014332/456258b6-d181-11e5-9dd9-9ff305eba2cf.png">

**Comment by pippinsplugins** [comment] 2016-02-12 20:07
@mindctrl Think you could look into this next week?

**Comment by mindctrl** [comment] 2016-02-12 20:29
This is caused by running the settings save through `sanitize_key` in EDD core, which coverts uppercase letters to lowercase. Braintree has capitals in the settings IDs.

**Comment by pippinsplugins** [comment] 2016-02-12 20:33
Well that was dumb . . . let's remove the capitals.

**Comment by mindctrl** [comment] 2016-02-12 20:33
Not during save, during display.

**Comment by pippinsplugins** [comment] 2016-02-12 20:55
Ah.

**Comment by mindctrl** [comment] 2016-02-23 23:33
@mintplugins can you test this out for issues 6 and 7? The bug was fixed in EDD core, but we decided to go ahead and do this migration anyway.

**Comment by mintplugins** [comment] 2016-02-24 01:06
@mindctrl I'll do some tests tonight and post back here when complete

**Comment by mintplugins** [comment] 2016-02-24 03:41
Looks all good here!

**Closed** 2016-02-25 23:24 UTC
Labels: bug
